#!/usr/bin/php
<?php /* <ViaThinkSoftSignature>
H9/BJZ8bpI9yMlrEz5VwYUgV1jXji84DfuPGxx/MI9dIk5v+DsXSeOkTwlr7Lyjsd
iaPAZz9Sc3hJ1Y01+ttC/67RpQMi+U47pvfwHIOcXiIR2CDyzb2sT1RMNFwUajDxA
TfZhSiNQtKMmRXKyJ/0Di8P2RRC71EFU/aPz9tkxnSqoFSzK2EQ+CLdDcGFLeOgpd
XFgMol+ydwjQVcqIGF3vbVU8/a7LlwaIG37eul7DepM8x+Nl1iOqmd+gXBLggq/IW
omhV7SZkGf4G56lqJuApFwRAJtMBP1FhvDXe+iVhwX5lKbvVoKRlEnW7+u7ac2Ini
3KhXOmE2T8uJm4PbCRqLhfqZWI3jolSNIS7c78PXqGv7oxtz6pRFJrF7lQrc/V6N1
ahbpu4gH9z22p9LimjFAM3+6AXDwVpdDqATofY1A4J84lxIFqb3HdOPEzw9V5PRWG
ymqA3lW7NXDPMqnGSGz4L+PAzRoQHlS1ub8qCJcceODJIX/wyTJ6RrXJ5iWSmwqPK
asQD5DJSZyR9sKDyFsSmeapTgwMfTYPdM+rIJ3i0nA7KDvWpsp0ef0LztJS3h2jkl
H54Q9qkNZdYiOMt+zARXIJiw+X2/EV/A5+fHx/7CtkhWiPfz4CKX3JJKFNzGAMRok
YHzsCKrhiw8y/yniBsb3hX0YUBAyLs53vB20QeR4CunqaHiSfe4/LRYvYjl/s2jp7
kSE1M+2+f5vGzEHqfQJExmkQxzwTKTRuKvdNYkqIaJ6kVGqAC8QidhJPVXxduXgST
q4xMjyRPW61pa6JCFQn8jG8RysR0FokEPdGMVd6yYXYFjRUpEyala1ct3eYXgk0PQ
U8xon4Z18q4lLUgt8oqis8x5sUEGw317uW+bhCHhSjgGJyI9yAo43WxqYPJKnQKUe
OA3wr/6OJ6OtRjI7g/qBYXcv38Wj62G9wQX50xcdo6LdeeLjgRTYO7q7Ypca67ZzF
5OUtP40xxwODnMuweDNbx8z0LtgdgtwTeNMzodD20aerw6nr3QFrCoBTdZ/eaQM7d
1F+eH6yTYM7C/1OWoywJCZkjPDan6IaqrFeyza5h5tsCVViXzaZXYZSGI6Q/qzo6l
xZ95zbFgbwkxQw7QMpbaI4TtMqd2oBRbDjcX5r8FjBW9bo5dseP4YnbrPrXnvoNAu
+9wOSpCSXSdx346aphKsjRKan0ZCKzD/bYrnZJw5wnlUET5h9NWUneKs4lJBAeVjZ
WkbV+N+967U8zDUBa6Iwp0XnjhRUVJfSeq4mLV2g0V7ZJphAx8oSGuFKrrd3El0hn
82FiPI8ABBXfRCMN5TFmQMmANBVexB5MvFZOOQVi7u4I2yWOgqOXYeqMDrmtA9Cez
g==
</ViaThinkSoftSignature> */ ?>
<?php

/*
 * VNag - Nagios Framework for PHP
 * Developed by Daniel Marschall, ViaThinkSoft <www.viathinksoft.com>
 * Licensed under the terms of the Apache 2.0 license
 *
 * Revision 2022-01-12
 */

declare(ticks=1);

require_once __DIR__ . '/../../framework/vnag_framework.inc.php';
require_once __DIR__.'/VNagAastra430VoiceMail.class.php';

$job = new VNagAastra430VoiceMail();
$job->run();
unset($job);
