#!/usr/bin/php
<?php /* <ViaThinkSoftSignature>
JECmzbK89A3spE9vWc+t83TbtGIVkkOPxRZGky06jmfgaJWI1OHNTowDly/6e3hXq
OXPC8GhdvgkGNOm4DiqDR94Q8bSZnnnjYJ8M0wU+RqOgGOZcxtHyxYh1cMt4+Nfqi
q0uh12HT7DeC133UA53/bZ9qr2zeMg7FhJV7AB7zSNlxyt3IcwS82soT0sZNVCia4
8Jltyqrb4LthTOJJ+DFDtSfuVNZhi4zbY7Hu7rzw6nCSLx63ZJO0EytvtLysPDHU1
NDC5VQGnehZeDH//Pp/n27bcU3bk5Y9rB/lsr/cy3Ee36JoztWcHO6pdU8BtB7Ym1
aXlFO2KhXG4E0vaWauAdoujDbL2gCRxDpsJsQxCEpM86mbaYbo3Fm69aJhxX/G5dV
NIkXfEqfRGF99bfiPjlSNwVPJAhViYnMgZcix/BoaKlqB5OTONoD0jrhySYI5WxBD
apczNp4cZv6ZpXBTTzyVxGaGbNmpCICjLfzU5em9k5VK3Dn18lo14ctOMZVdcHhNO
dtqxTskIURO3X1NePMCoOTI/oofXAxAaAEWMcATK6JbqKNpP4TDY0/QAigTVClowK
9+EMJHvY1oVAbOV/3etCcY91tHLJJfQfpx2M7xGrgz4Shcf3Xp/NmdxV30yz37tUV
tmRtte/D9cx9M6tmS4fptWHD+L53PKYT1ul7nBcHlcX9csxOKstECV95BjJ/0qJTK
mVt71TRD9VsSsQQtvEHTydabemcTYE5oYnhKpaPEQdTLnMM3yk0H+qwRB1yheZCWG
t85pqxPmGkZwxBta1j6uZTec/nvWbBxJRkzZ5Oyou9IM80eNaGGD96FsOhv6i09bx
xpRN0bTa5IrZK4szxnpPgW5bmQOalGom32R1KKKriuYK4brEy1jMpUZAlmN9LrphC
fJZFXuVbBdWe7cWZ0F+blbrlLbTMR1LxpF1r8hlKIqhuf1OMysbkcqEA303cMdlTa
USokJw2J/bgoa22GLRW5aSpUjqjm0L6MQqu58TZT4NhB5VRXo0ORZsswI38/U8Hho
jJ9tSq+x39ctn0uMwI5PBXOvXbkohI2BGkwo5YqLNTOV6I2uY1cEhMlIu1zg1Ocri
bTlCPIhd9xT91EX45AOVlOYEy36k2P3AfrOcAjiFMDfcgVQlzxjHYv1IWUfe7FZUo
q5SNVMdEWVqgwqHqVaZ15KgRNlgM7pQ4uDb6Uf3RkJMLZOgi8I4uLi5pG7zAyiPC+
7wSFSgEvkH36/hBHWTnCp2zjdH7gOkPD2I6ICNt02XQ72xG5+J45c5vI2VY3WCLK7
VeHjdoBvGDgzVCWU3jCmUFUzt8wiupkeCkpQzh23dCFLrQkLCGMbfv96tqIC8a+jB
g==
</ViaThinkSoftSignature> */ ?>
<?php

/*
 * VNag - Nagios Framework for PHP
 * Developed by Daniel Marschall, ViaThinkSoft <www.viathinksoft.com>
 * Licensed under the terms of the Apache 2.0 license
 *
 * Revision 2018-07-15
 */

declare(ticks=1);

require_once __DIR__ . '/../../framework/vnag_framework.inc.php';
require_once __DIR__ . '/FileTimestampCheck.class.php';

$job = new FileTimestampCheck();
$job->run();
unset($job);
