#!/usr/bin/php
<?php /* <ViaThinkSoftSignature>
Mzlo3XO1AyetqTdWdp4c5CngIzcUyos2y4JIyI4Y5Xt3osdutrFth/1x8muUNkHZ3
7a7RrR5uM4oTKnzgj+seixYPeRE5CBxN4Ciqe7jHDFMxjRehWL2ly7Oq5WVhrC1Ql
jKGBU9/cHtBaIEtcqkLilBX4MNN4PLuuvHNuI+6qByg66gSGq+Zwt5fAW+4b9HOHx
QEPOCQXWx3SR7SwSdnoM73znHWsEqGZHie4UnGajoCUmzuj0ONg2Q8k3g+n+o838B
oc2TnWafkjgaHgCf/m0J2wH4z2V4YgtFRZ10DF6UZN3k6Khgc5HOL1IV2le0mcTD7
0b1JYghEXXgZYn1qhoap9cBDbSgtwjh7zxEiEzy5zP31r0+Ue8H+puuJXhmoBHopO
loeD1CWHGWJfoGZ+lKOKTIQJOpVDBLuHIsKb30rBSRgQolcbSpqmlyWgCVK2LTlci
YXYb76vDd1yoNaw6slcuJswQQCwRSmn59xgBTy9MMOLRXxv37TMgfzvNAeTZ3HSrA
gGkzRyMIM9VrsSM0E6tB9pBS0kB2CEttzX5eqflffYmetM18WtR33YWqVkUF9SxeF
HP1Rd5d5siA36KkYoMBkzLm+kb2GvSM4N4gaA1rV8ZYY1cL9OERfT09aqfoXAEtCh
88a4HzbyDCCN9zAhl+6PxDDHR1mzUoUyk/Eps6CF78Hp5AfEX17WIxC18CdN2Uzvp
TMCc+fALRddKxGg1he8U6zf5umkCWFDAAt8oeGcwm4Se0F+veudgfq8wOcT/c3EAF
VCV3BuVCZJLBSAiYCJXHY8nbAgWhmfU0M+tu+HKqgzrSIXxFxvpStlTZ4D5eI5ool
GdwJiDbP39lLLrRFX5fVJvmzMzi6Tu/1OXW6p2Cx8Cy7/GX6qW2wusEUUjQWPl+F7
N4P/X6z8g+/Sql3UgmEZBu1qZzUwXYczhXMPUloSiSK+SzDFf2o5wjXJ/gNks/Wy5
AlPvdxa4Qzf5cCITL8jbWzZurVXW+UExZMYoMNDlk8jogjqxr90eoKINJYaM3WDow
oS84FZzxWAKrHGUYhKTUAJETC0zwaYI1j94XEktxU/1NBaEdVVbf3zr3DU6xbWHqV
nrO1Cs7TOAHTiX1Z9rfo3yIFUnmOAAglfDGJCjghdudp6CMebKRFbQLEfg5J03c+p
San/yqgz1Nc8zBOe1hlAnXZsrzL3b0q/+YGfhHQmh6kP9wZ77IKjfZ4RhvBckUplc
B3Cm39j2lgBLVtyUKWopnVVohpakMgw9FuEv0pOGFaDPTibIbgkh5QRBLasrnn5+H
bucke/IfJq8/svSKA2JMfYVjMMudOabsRWYgZmLTx3od3dKyrb8YrBimXUoyl43Me
g==
</ViaThinkSoftSignature> */ ?>
<?php

/*
 * VNag - Nagios Framework for PHP
 * Developed by Daniel Marschall, ViaThinkSoft <www.viathinksoft.com>
 * Licensed under the terms of the Apache 2.0 license
 *
 * Revision 2018-07-15
 */

declare(ticks=1);

require_once __DIR__ . '/../../framework/vnag_framework.inc.php';
require_once __DIR__ . '/WordPressVersionCheck.class.php';

$job = new WordPressVersionCheck();
$job->run();
unset($job);
