#!/usr/bin/php
<?php /* <ViaThinkSoftSignature>
1tZ2zhsNDzqmhiH3ABR/vEURfI5EhJ84vcNAwcQE/dQg14SjH8n9xfN3LhkIj0cnO
7Et2VtRIwFVI0i/px+Ll7nNgMT663r2w35BVBU4XDnA/ndomCR0P1JU8aJd6AsB72
Ywhc+c9C/YsOEtfEVwZrfjmhv80S2aBIglBlcJ4dFKTpkkdECH1sMaV5xvuT1ISFC
f9v4w0XO9m7r4CMxYHbzDkhDCM9mt5WjLqOsTAtpGiNtwpaRpa2T8ruSF3fsXwBqG
Bpw+vQXgV/Znka8QGeTzrmlH/sbnFhyW7VFeoYCO49o+d61eJzovRExmzPR9vvhmK
SoZcFPi5hAt3xh2OVmtuMTP2946C62UVsSZSI+AHCIjyu9Oi9lrZnGxrupqGp389R
aWeuvv8xgh+PcHVMU1+vsYNYh4f8lWUNzXUJLodvERrdKGt9kSH+4FQk9oiBFfz+T
biMlGl7lMgp97cafEz2JvupkUG30cH+VzQNNDsCNgYdwKs5+d7m9FoGfnpjXm6oPR
jRvvA2nTwKQaOFp6N8UlIbt5fnpnqLjHu71aoARG/uhVjkxKGmMboMHwjdmCBMoeO
gqJN0Lt043rjoAN8bJhf2cRpQtlcNO6ZdTOr1tyn3HhkTMj3m9mEZn1CYYGnGisUY
r+se5bmq6Ki7Fo5DdGe1d8Gg1NVq4zBzhCSj5rR2ouQiFgOkEk8yDZWhpI5uhRpdy
tEqeF+H3SXRkso/A1qqdpr9lSz+FnROyJaw2afEC4MwRE0+GrVsnoxV/Ygutc4O45
qTmZ/JRswSb/YsLVBimRtujyHrKB03WutGC4SQIMRYJ22JdfZVys5HfH5i7GPSrDr
4W11wEuIuAmO8VALaB2/+waSvaBxNoU0j3xAq/M8X96yexL6jOUUEASmDmEboK21b
Lb0coNQ0YT0zWkm/OUo+a92k3mN+YoueEOumxQMgpHOBYfqYETAq/onkbnPaIKYUd
qsmClJ6OWcaBZBlR/V8+Xzrp3Q+PDEVFanz/wuhagkz5ar8wEE/MXsyTk+9CsKY2W
xIT+o32+kJRAgP/2Tt0rUJDWbD9IAyTAT5Sd2xLdsO7GLgnAIV32Z/AE7fCfcSRsx
RmpU6B6zskOlOBto3ij9sKui8F5/QVUjmdSo698jMky0nDEnpXCRzdjcRYEOGbk1Y
bf6RwMR5GLMfXYtHRcaMoH4EDLxWnwoGbdYXe6sIRtfmgGL7G0fj8JiidekWqUGZG
yU6ucbtrp8vFkHY5JgCa7+lw0sH22qeozrDb3chTSgqvXFkdGOzqXUPpO1RgUx5nC
pFOgPm2TrfE+HittOIW34NlIwoH6i9kkQ/FyqRJwLWtla4kuGe/A41RtEbutt0FmZ
Q==
</ViaThinkSoftSignature> */ ?>
<?php

/*
 * VNag - Nagios Framework for PHP
 * Developed by Daniel Marschall, ViaThinkSoft <www.viathinksoft.com>
 * Licensed under the terms of the Apache 2.0 license
 *
 * Revision 2018-07-18
 */

declare(ticks=1);

require_once __DIR__ . '/../../framework/vnag_framework.inc.php';
require_once __DIR__ . '/VirtualMemCheck.class.php';

$job = new VirtualMemCheck();
$job->run();
unset($job);
