#!/usr/bin/php
<?php /* <ViaThinkSoftSignature>
Uf5W4vCIVeZkNXOMmqzzNeGEOaQyaWpdUJWOcxKmcbCKXFKZ1LmpLMZmbkiDJ48nj
J9v/OtdEta+QNPoETMsDwSQAS7wFQUbUvmj46t1ap7f1V0rh7yh6qzFbQhSezWU+M
k6WIeUXiO+NdpEJN36prt60T3SGiBapo6K/sNneglX4ltAnZZliF+keFod07/BQfK
txCHQ0w4ZgEx69/uK4r9ZOQg6rYFG1JBUFSX7YR9kRCyGpDNCJlXMN6b5Zp2mT6ep
OD0Ea0cOXVHiuSotqmJBToC2xahl4hO2mCvu/4oWv42TtG4/J0I9oz8FNW7ytvikS
t/QfiFKZErqad1P4SibjuFHk9JwUYlLzIAL4bIvWroLgwx4xVO8LtViB8iaknqOa5
hEk0a2HZk/OrowMNCegQgoTpah1o6CZuZH7Dm8KMFl4jJarT+u3U77nQTASUsjfHz
wkOP/KwVhsLOrka+RYl0v64EKaDyX0M29pcI56w2yHe82ZjvAKW8Ju1RZEreRV5QT
E8xTE6qOuOl03mNMuVV0CaTLb08tUfa9AwUGoYYxN2t7xdD1yy0oFaHAiUcvaTNMN
4zPfDPce6ICQZS360xmLUg3nvxYzmTHD+s/tXhc2Kb4n0cSVznuDnuEZte/QXgKoi
w5g1bLsdPXQk5R2Dq1EB8AyDQUUNlZd9VyzBkwAhXAfmskxRJvPGgEIvoQC4y8QsW
dOtvIW5It8WuKgbR3K+6QI+QgNwnVtG9NRFnIHLMAR1rTEm4cNsFetcyQaT4UbQKz
Re92tp2ibI9Y6551Qnf4UdvGDRDPQuOAexb/ROlExuyGXUJsvfP+TQHzZTe6FLVmv
nKVvrEDUfMZvmV0YCWVNI4lN23PZDwl2i8516vRhbqtosnSw+60+mMDFk9g6pvtP6
DAc4Hb7DkfYy9XsdUD+0a5Bt9q+E/mdHBnR3PoR49KgGU4YdzrYm6gelWeGoU/lD7
Gn/7qQCIF2Fj4fWSndlxNeZqM8f+K42FYUbPvhwy+De0gUOQ/C7QWIVWp34HjSOgq
QU73krqAvwDD0h+IR1eREc/vQKOLOgNGDge8Po3g/EEwexJp6HETL0DAZzf5JgtLL
IFk0WMRl0n5QrvP35K9RhPAjPSxyVPt2+jDJ+hQ5rb8ugw82O8ZcxQb3n06Oyqw0h
Q+flDKBuUtryytq4KVu7QnfkKsnDPyMO/HmyuGQoUkYsxUNSQazhsZh+38dQZAawP
wFuWhCLSUSwf545jsOHiz2i5/7URxFcF4I1X+alv6zQenDVT9nGcjok5ijvd/e4Ei
Qbpe/A7oqlOJrgHNODRuS3jmHkmRRa2Km3xoFbUrUkWODhPvEQKXjdhWy3bfMymMT
Q==
</ViaThinkSoftSignature> */ ?>
<?php

/*
 * VNag - Nagios Framework for PHP
 * Developed by Daniel Marschall, ViaThinkSoft <www.viathinksoft.com>
 * Licensed under the terms of the Apache 2.0 license
 *
 * Revision 2020-03-12
 */

declare(ticks=1);

require_once __DIR__ . '/../../framework/vnag_framework.inc.php';
require_once __DIR__ . '/PmWikiVersionCheck.class.php';

$job = new PmWikiVersionCheck();
$job->run();
unset($job);
