#!/usr/bin/php
<?php /* <ViaThinkSoftSignature>
fWU2TFVRhDYFd3cF/gMFUU9vqavaPZVcyhrw4QyATK9E03WL4RAfM3y0KejlZBC3k
mkzfCwFpeukjCIfOCkYXydURpnGCn5V+BqGmcvXp5VdQOHufjHjCrLskD5HMmghWY
N/iSVbCVdp3S9vXwIMyj9FIHv0FDeRkCS+AVaRuHhus3P64ZkOodm8pxxyCBblYuo
LGASFf8fh+pIuWSKRsItn+SVU0nHuvlT2/GQi7E1vl1zHoubUn49/9tOKQWLa0YPA
j8CDPkbqvqL5e1evJnoqvULMX8HSAlf1YCAfABw8Z7LVQU09IDSGjMZ8WyIxRibGO
lXZZZR+uZQQEMi0LDUxR1/QK1FBNdkhAjD/P1hXsabScP55CiNSJOOH3nQD2eCIax
dHuzSc+kYW019IcPIkDLsJxgaZtZs6ySWTJ42c54qFsheVBm9CaPMlguq4WIh6vMu
AlkRtvLxaOLeDjhr57W3Z6Zn3mKsRnyLW8NgCnEg7yMfM6p29aiOfrxLmfiwfq4KW
lOBpr563fru+sBSs3OGKbA3h7ca8pnzlseWI2ld+3sp7cjHBZTO07phVTz2imqMPE
2Rt32jIxE5wIeUzU+UxcjrFfAxxdLzhjXZ8RCWiWfgdXV8yMbuIdy8vzJAKaO/f3g
+RC96e9/LKjEGyaDyyVPT2HEBZrvvnGeiT1PVMqdKa+YG6xs4m/jiq53yvUUCk05t
+qSi+9xz64qHCOBIkUKHhbb9doNc68Vw0Vt89QOCx2Zl/BOgQCWJ7lshCqlEjqTWQ
3cy6Mcg1197H0RMUJPz1ki2CRQi1B0UKf/WTs9VUXngcDxFGbS35dFFl02cRfPSEP
Vb9kvB7Y9CBEmEtnHr8Ogr78vZrUy+69AnyV0S+ny8nisYP6QzSBOLkR/Dd7dcq14
EvmNnMd1C8VaFULNd7Bo9FHYo+46O+GBgRS9iE2af+nZBL9bpYfYLv9tCQMb3w2wA
dJR0bjlIMxL6LGduQhD7QUwVbJYJuE0+vIsnAYZyzGstEFpozfdESn3Grcc4q2FtF
kSyEh/JRZZlsCXONzEwNjblnJigLYfJ3pBVrRMY9BERGhhyoHT/Q6yNIkNuJpBnQb
fJx9RvDtyr7lIdZ6I0xtxEZ1NrQQoyp9w0GaDwagfOqzXM8UOqdIEZhDVdR9ZbC2T
y76ohuAL3qOFfFToxPkVJ5YvXthXs51GjfJi8KpQCb12XxN8WC8qJHT4Y7ElEZadl
Lvxl/a/k5kWgdcGaPtBaoTgLDF3jjm2wN1GF3hHhX0BkGuLGFzbeLDxvGRdB9h+ea
aAH+5cewEVNVXcLbSaEah/p1Zw0iw4XNyU+WgK1dKWH16mZLWrsYc5XpoTszIpmDs
w==
</ViaThinkSoftSignature> */ ?>
<?php

/*
 * VNag - Nagios Framework for PHP
 * Developed by Daniel Marschall, ViaThinkSoft <www.viathinksoft.com>
 * Licensed under the terms of the Apache 2.0 license
 *
 * Revision 2018-07-15
 */

declare(ticks=1);

require_once __DIR__ . '/../../framework/vnag_framework.inc.php';
require_once __DIR__ . '/JoomlaVersionCheck.class.php';

$job = new JoomlaVersionCheck();
$job->run();
unset($job);
