#!/usr/bin/php
<?php /* <ViaThinkSoftSignature>
q4fVaQlWCwd+K+cPGaWhUrMTGzy+Gn7m70y7XeEyFhsLGENE4thlUV52IWbjVyTAv
odnEesAZgFauSu1wQ9EwIYuFr7C26e2121cikcUY8nz7YVfWt344x3MYAmhtU6l5b
Suf6PkxUqzE4tlYH/mwf3/vG72k7ykN46AJiDV7UvoOaeOCoR9ifSHd6IAoD80wvq
kRtv3LNEB0Vi9Gi9nLesu0H6XZF7fil28pZp+Sr2sgGph1YDzpzR6OV9iQk99OoBL
FrH0CnputFbUrg9BEydP3VRpzQULZ2UFGBJAjo6uNV0Vv/Rf3XuVVUtXvla3Aifhd
hyH54/VHA+/BxPxCG6dXVesgGl+NP88eGQ+s5YBY46m330DNL8g9lH3fr0y3DEUDf
Pi29KTQB2G0za7jS5yMWRd38dO4M3stLC1mMGqVZ5w0oUIYrJ6TXEDuX5rTM3Op2O
B+cfeBpPQ51pfbtba9Bhi0o7q2aiL26GQPVtPburg2shiIfG3O1QP6X2GIugr0lQi
6vEA4O3cWuh6nupltxX7NeQ6c51lU//xMBgJr60VHK+7yaDykCWt66Jc7XAemK/jB
lOZCsozZoDLnfWVA0gybO+CX0+FIntb3LKZMbkgyF0YanNpbX2dmX3NCqZyqcuLKK
jWivMyRZtF/wEqT38Vgmx72Cgy0acPozBa38rExqA2ZBh4B97dsAfXKkX2GldztN4
WPbwRryPC2BIRIzSRnmF788ocEzXBJHFn79yHToRxRNFh8FqpVahFOl/eIh+uAC3C
9iZKBrC+hFaclrmQ70WZuBQc2SEvLDodF+NFzRCFee1/1lC4VBgynZo2LFYYpo3Wp
qZ6IudENhVN03oUgFGopOSsHefJPp0Gb6hw2DXjPFcHhLR8QbMw6uCGmBJUsvVqwj
efcHG7r1AcdIFFSSpeZRf/Aua/CkLjSWJ0TzMrJhS6LzZnhxf3veDN55mGvsTjT5z
+kaWXyDNnkpr3ghtDDD3L0uWim55YiJG5hqDawniL5lsAoAsbvZm7vgPwuc/dLUwT
8pd9avpxn3uPKn5Ys24qLnQc9ghLw9/382KBO+ocKLrsS87jfjePWnTimgTw52NNa
TwEbW2CuGA1WMjapv8WYb1eXmTluXEja9Ow5Z5Rr2NR6wzjNvZZ4u9nEC/Wy17lQS
JatiDx1V0EQmUzp8MUqfm6mkqFFDJgCHZ5KgvvyZxKAuLWNK0mebl1Shwiliu33rH
d6soKtu0kNcCSHUTXGy+pK+9fwraK61PS3hcu7TMAnk1L4q9VyOs/wUtbpbQGAEBR
EiFl5Gh0F/XXprnQFkhcptPprPngGTGtIZzJaLF06zXLqpvdjqw+nYcIfBJeK7RD9
A==
</ViaThinkSoftSignature> */ ?>
<?php

/*
 * VNag - Nagios Framework for PHP
 * Developed by Daniel Marschall, ViaThinkSoft <www.viathinksoft.com>
 * Licensed under the terms of the Apache 2.0 license
 *
 * Revision 2018-07-15
 */

declare(ticks=1);

require_once __DIR__ . '/../../framework/vnag_framework.inc.php';
require_once __DIR__.'/VNagWebReader.class.php';

$job = new VNagWebReader();
$job->run();
unset($job);
