#!/usr/bin/php
<?php /* <ViaThinkSoftSignature>
fGSssQ5WiH9LfwSUqhiDzyZMfWbfjEBnlT8HfyBUcHSXiwnI/ni/dG14gKW0iq5H6
RvGE5C3Zdh4yFghcT4M/RjhDETWCzpD0UgGMpXOaHCT4vmVOIfm+RMC4DR5aZparl
4BPJv+OvGOzwaLKIxXQYZ3nwTAoUwOd87+dYaqUPl515qw1qAygcGZE6wYLu1XxbV
mhk3cSW2t/uO/u20XG4CWcl5R3Gu1wk263oY6zymEGc69HBQcGOTD+BSpqd3qMRhN
iyLRrvYyP5QApqmN3Hf8LAnnyUCJQHLBNIukhK8U7U92mt6gdEN7pSxczF38gOHBd
W4jll4vvFE9EcM7xOd9R3IfxAiQjKCv73CaZAta++bLaGF33VOo/oZQm3zuWi/CUf
SzUjrJOIEbHJGs1aKas4+d34+RAv++puu5zAUD+7XbtzrsahQa8G0z8TkwRq35Uvn
s+M+doMghfDRhx1WUCgijXgRA7fT1hMAjWDtFoKyWCjXm+BhDHT2GLPS5jDLRr9CA
gI36LumNQ/M0DfIQYKNwOMVK31lNszLOzQDxK6TfTvJQiwTdR8JW0xo4xshq3eyiH
arRJNWDRXDQI6DpfL1QjQatetepCraY+DunTxGFH40L4W8BykrHpcXavJYWl0Fycx
udFyGXFHYA28evMMmkyMv/B7oyn5BFPvt/3qDmlTn5dg130jDgMBfZVNdhTFMOkXQ
mZaig8GenWHakpU+iP/tkl0CL1a/IzzEtMg+tA4GeV48HRD9Y/2IqHl+gTNF8cpDR
VY9V+9O6RTHdn0WhuddQwb384wK/frOBmltzNg+XFnO4nfUXzAlRY73ctqpXeT0Nk
9G0nMm3wDaAKPvlgQclxbhOIP2KbypvCRzUSr9yTq/uKxPONOoybPoPkIXH8aNpxU
frSQ+yCY5xum90K6MZaMmGDz2o38Je/HJsZbvzeMA1NDcBQxqlwDppbZbcG6ehV2D
6t7/AdObRca4kXh6lIklmCajhZjcKnGw5Mbb8WCCnbeFLYkTQk8knBMicHnZvrNwS
bAuTDz0AiDU4AkRfWfragNkDi9DTmUTTIrzg/10miMkLnoDUCu2RK6u2RDFr2QSH1
KznOfBJ7TBYmuGdvLdJerB282h+148aP/YPAx9oS57D+7ZOHAYXv6zkWcaLV8X+2/
nGSfe4KKlK2zLgPmYblxA4Dp9xHVoHKsk4UPix7KQjNln1F557AXPTtSLkVSBzf8m
quqhmgDC0F41iiRLZZJTtwf4jzvDGFVkq+C1tJlh+NU3fRTdsqPcjG63v/jMCpDtz
atgZ+m3UT+75nNIPACRt9kJ3XiDiMk+pI/VS6L6FtAFEuX6GqFt0B2tBVS2pI6blh
A==
</ViaThinkSoftSignature> */ ?>
<?php

/*
 * VNag - Nagios Framework for PHP
 * Developed by Daniel Marschall, ViaThinkSoft <www.viathinksoft.com>
 * Licensed under the terms of the Apache 2.0 license
 *
 * Revision 2018-07-15
 */

declare(ticks=1);

require_once __DIR__ . '/../../framework/vnag_framework.inc.php';
require_once __DIR__.'/VNagWebReader.class.php';

$job = new VNagWebReader();
$job->run();
unset($job);
