#!/usr/bin/php
<?php /* <ViaThinkSoftSignature>
zG+SMY7yy4L7Orhm0vmFe1Y3jA+a1XAWbCM0brMMPzXvhZ6Vz/dMb57e/9QFyUgdj
2u8RERhxYm2x/wopfb12Ii03fqC1UZt/OdmHIMfiLdf11kp+jc5nSdvL/c1DgaC0j
e7of7ncSHQ2UKbO1zFZBwsRei69U6ZeDWoXpfjFZY8ojTDUlVsuEzC2T3V7v7+4sR
juDmNcc71ZSMmNQDSPbJFt04kpGAenlZmpPa4nTJprJQAjmt4s2Z5xa91HWDXncp/
GvbAjsMxUc5g5QQMwsEDFVj9PzoTJvSvinGyJwncUUIR9SMaPJBC++GznjNrhnDOC
3MPsEiXQG6qb+T9vLVQHyWSa3DrkBj7eWOVEnN4lylvgod/PUnHBXKY4myFFhYW+o
PNn/zcn+fVPoAGFZn2zmFsJCw6o5pruGPMUEoMTJ4O3V/uYMYNkNXkDWFjhdfPglS
5In+bU1ab1hT/wJgqAx3HOp1bycfgiA7SpsV9C2p/w3Jv7bhr2Wmvn5w9xvt/biuj
RZ9tlbE0sAvtUQxhkrjTdb+nVA70FVCu+0cLaS3dUXn1Z2f9KxGIIL8XU141HkT+l
g6biAa5r1LObKKWbAjnNg6z8PoOwfAf/h1EP/VTbpicNrC+lkJ2gxR4iDNB6N8ndB
7xg6j3UyTFKftiPxxnUwXoPb5zO0dQa3ER9+SLGgWFQFJk9S3SwvKGLupTl2KCun9
kPTG4wlq/QyDMxwXI2g8KdqmHmr5SwjLmRDr6x09rR7zbrV9SRmGDmeInbzSGV/kY
ohxIXSfknzRbKUwyewEEgVvuS58NFzsXDv+CJe8BWfXmc4ZgBrxUx05HWq3I0Ju99
zRvGMMXN6XY2apitbPVE1NwDLDWCVTelEqhOtcUiQtJkLCHDsNouuBV+PiQHNt6R+
kYtbva4K+fhw3dXzDKBuUc9Rj/1pEGC+vUdTE2p8lvzhXp46q8Zt9ve225Y0J4SZu
7QWxjg7e2MWHaDbP8PAYu+havSm6oNSQL51Ov4iGWStubujYLyUcOdjcrCwObOytx
yfz6g7GGUiItNXCVB8t4Nh1bz0zhvpvz0sOGX/LP2PSLSAUjCjLRLfNeJI1D8ONK7
CJfwrEmO3U+ma6VSxy4Zop4BTf/8LsItW25eDcOfVQ194gRtBm9+FZ1GSyKqzig9j
imQR/RnlmfVroLbCPw5ILje9HO7BENx3fhCHnnkhgJEM340oNQtjaXMM5eJTae5Ue
P2vUOEgCkAQz6D2Z26HdNQpw70VK3wk1FR1WiPRh6PFRZcQ+81rciToLU37Wu49lp
qT/ossrEN3siX0MD7k/rT00+EDxrimCQXEaJ19CSIhaDVtqIA6Omo0Z+6MLpkGdBk
w==
</ViaThinkSoftSignature> */ ?>
<?php

/*
 * VNag - Nagios Framework for PHP
 * Developed by Daniel Marschall, ViaThinkSoft <www.viathinksoft.com>
 * Licensed under the terms of the Apache 2.0 license
 *
 * Revision 2022-12-18
 */

declare(ticks=1);

require_once __DIR__ . '/../../framework/vnag_framework.inc.php';
require_once __DIR__ . '/WebSvnVersionCheck.class.php';

$job = new WebSvnVersionCheck();
$job->run();
unset($job);
