#!/usr/bin/php
<?php /* <ViaThinkSoftSignature>
BAQbDgRTr76NdKkzSKmQyWooYpJbFMx/0iq2M+ZbMRu0Lz97dVXNop/fRkpTBvuCb
4gT7JqSLEjXZpA5/F8pxgJSodglJeNmA2snbQN/Js+jVu6jdY08mScp9e0IuM/SVp
10RHZ9AkEoSQ7AhePaR2WCBSMAc5D10S4XO8UsM7xfXfAULkNOrq/ReUurat6FNgS
OotTK10SFjEv0/tRbYy9NHzcZxmA817wWf3vx47ph+B8BWbJlqgnvk2ktshzwgF32
Kww2luLUsab4OGJ28oxobv95sTBsewbalrJB/GRi0NNvpKuadQaPmAnNkOhRmiqqr
iD0Nueh7zYCWNVqagvBV4j7M7SjQ42DXQQnm3JFCeFbh1+UBlDGQg/IaHhh0mwcsp
KYtoX+Ja02WlA9yYVOtyizN3tzoVGAQwZ9pVXs1AiQZp0cvJ/iOkCZMq0nnsZ0ves
eyNUxIzhyBjvQTQkkFKPUXk729xVdy1D7Sksb9tauOvRKtYTOktCDflv6lXNzwgtr
B/s2bLOWNw6mzZG657HnGJRG4qWBx5tHLbWJFGc/xifM7Zrefz/nO+PNKE9oZvG9E
HSiYFdZdC0dJuesZqS+ouWXfVj/cBO5t9bRVUBzLIqRz/9zE3a9vyDC9kNXlxu35n
mWVxI7ziztmFyAoL7luQOXx3cy1GYu9/h9plvnsQHbkKTocWLAd5tLKUWYUgv0w6/
gPuF06QvE38Ui60j03U2eXj8OgB1wUu/MkTvepSo/VhvJqeYE9rartSMMu8p9LpUn
fASI79xyFxZbkrJTsLI+t5UJLV1tAAwBykjy9obmPgZlPokBHkKQw3iFtZtkt2d3s
BeROfKVniHW7gItYETNo4ICnbyHON7QV8Ue+Bug1Rg0IuMl0BNB0xCAz5IWpVUqbg
LqEtoZZ/juKXt09j/bt+TjQ1m5EBY1/TSHyV9uijImxjf1p/U+NkmrtOomOmJ7A7E
oO2lAOTx74C1GTc7xFalLUsp7mcGeqzYnNGG5viNdZOIfbyASdKeJILD+a9YYyzHa
04Rodx6X+U0OF94jPQWyDK21/TfCbqOqdwPqCO26jeyIM7qpmb4c0Ie1zlhZtcgHx
Im8Olzngf1w9KxjF6N0USfodZ8bu1DiX1Az+jqaOVUSCuXHcqTlvPMIAjuM8olhM7
+fhfyK1/eKYqOcwTE+4emRwWJ/eSLx3mego1Cph9MHt6XHaWwjXsKC7fOxMHUNAyq
Nq5QrlA2spT++zkDJarqijIOzZACjWEpXVVshOLODFkXvoYNxL1LQvr4CPtDETo4d
bJPF6OG34alt8XYHu1nrlh5O8rW8VCf0CcLJOuzT0NOh7Kad8oaB1SisjxLXo2W0N
Q==
</ViaThinkSoftSignature> */ ?>
<?php

/*
 * VNag - Nagios Framework for PHP
 * Developed by Daniel Marschall, ViaThinkSoft <www.viathinksoft.com>
 * Licensed under the terms of the Apache 2.0 license
 *
 * Revision 2019-11-18
 */

declare(ticks=1);

require_once __DIR__ . '/../../framework/vnag_framework.inc.php';
require_once __DIR__ . '/PingCheck.class.php';

$job = new PingCheck();
$job->run();
unset($job);
