#!/usr/bin/php
<?php /* <ViaThinkSoftSignature>
mqBnKaXSvntQ2sKRBSFLC8Jre/OPbS6gG7zOOohQ7UABuNjjx6B0QAmobWx/gr5mD
66TNU1l6dl/GqFkVssrXZmX/W2FE39l16535SCG2PtitBHjcU9S9WNqlaYAvegNik
mlB4cpjL183hJHDvhQtijiEaO+vZJqqI5h+KHopeVZi9eT5vqFZ+kfIxlGWhXNMjS
oSswAiVLPOSfMQADA9uGA6dcSpvPOpR/T6ga9EavD+9sCNaF+ToCLgTEMnMUmEn5X
hk/z1TjVXuLs52juiRjZT3XN21f1oKJOxa0bLWWzSIyyg2+VjgC4zaGqcbJzDDxQk
ghnftU91HePNtkcwxZJuFTNwWDbg77+hObkLz8gQ/gPBuGcRlbdrIyuHcHdMLlRTB
oa8h9mmu8u71E9RVAZteZAT6ct0Io9nQJv/wVEfZmFw/WBN/YGHy7HYEqgtuHWHeU
vpSjT0eOxoDZmYpZXF1uhvPnLXBqhrtJJ7kDxL3kZ6Tgd4i8d7hSaN7Pbq0JLE30H
ri5Onw5cfh7Q+k5/oPxWsTLsrIQiAXKP6THaenFkeLK0pn1RtzMCpJZIvMjHW4FhV
LZrhGB8rrQu3gbdi5gYLrwx3XOA547guDeHF9FTB5yj9kE2CR9P0ubQjGpMBxiyfB
9AZN5q9aXSp+NkauHfqUiArEbApwMAnGuhjjeeWQ5+IcfYKhZqev9+O8lbhA0Oz6k
LbCGJQ8iLaK5nN85t/x4buW2n1emS6blWYGWXMEWRZrue8KhNnpK5bdd0Dyke2jHO
0/4RcYKrdplh++87/Y8JI+bBy6mFHKYMJgkxd/b2bNSQ4+WLUyExKs3aLAzU/Gu0M
gCczHYpEuHqENqpKZpBbo5MXw8Iqi/B6OdoH69lBBXeeKGTv3JnhieX5coDyPIW/+
BUUfS4NsQ07LhXr2bAAmGh8JXjRiGS98khzqx86icEF4tb7cViwzJ8bbTnLPxJquk
ekV5hjDEcO9CJ29C6Gimkl2FNigj2mayjZeRZbjk5owWC7OPzdcaRV/bFKpXzU63/
eJHcfQVHQH+OhrvWCwSjFxwSxzcWKZMsI9UwDELTW/LfcI+XDtQEtuDBI1K3c3pD5
weuWWs4RmAx+Xw4Kga0XVW4FYXjShNMl5slvGJZUF1WF7iJs18ZTL6jqDOyuzYO0D
ZHdPKqPSZRRT70gJgWIEigxrYZKIADYNlvirzn+0gu2+g7k50X3153wJ3W89Cs0v8
LY8l5qHo9a+WnvbNkl7zOgA9WBEAeM0LMTuOF4Q6f+3s1iTnlXB5RgjfbIG2DDHDr
MOtvwNWaV65YiZriO4VAmBjMqlWDW9cMUIGU2jiMU3RiZQmgiL7CRt6eBwWRiJLxD
Q==
</ViaThinkSoftSignature> */ ?>
<?php

/*
 * VNag - Nagios Framework for PHP
 * Developed by Daniel Marschall, ViaThinkSoft <www.viathinksoft.com>
 * Licensed under the terms of the Apache 2.0 license
 *
 * Revision 2018-07-15
 */

declare(ticks=1);

require_once __DIR__ . '/../../framework/vnag_framework.inc.php';
require_once __DIR__ . '/FourImagesVersionCheck.class.php';

$job = new FourImagesVersionCheck();
$job->run();
unset($job);
