#!/usr/bin/php
<?php /* <ViaThinkSoftSignature>
rFtb6jP+AsAXmTUE+8iu2pORGBWeXAckPLtN/B42PL9cH3hNjM52e2j//r0wnzjjX
43mfs1DY9V0wIqnj3ZHyr1T2eahQBieE77aoPjXnrDo3q9zKYGXBn/HYCe/GSy7P5
UHZr13+qg7vOtbRkShY1ocvDMChpOUqFeoK6XTHIrExtGy36mmD5BNnW5xGwlLscS
Gbq6KEmreyIfCA3K1NjHn6Hw1MmfdnglXGHzN7YpnjtW909aFmgYScJGaddwp29TN
JBA8oDpxsOzLT5iskEq98OzZJnhwuMClSEWgKPIJVqQy4lIzKD+LgDaLFZwc2EM7w
dIICpv8rYs9wADYn+zyIiCID5T6WziJRv9vc0jJKg9NGDowJehfKPSYVgPpPhGTzt
vovnoXr4GNOSKH0NxJF7q+vZxsiP9OsFJXWgtzdRG3pdxlNaT/KhraU/W+p27kgTz
54iMhkkShx9EskOP5vFqhlNCuN4pcvKlB+N+pLxGLtHQ+N400aPD0WVP2oyS/1sbl
PpkWuuUookWSQK1cTBf60kYqx3BOkn3JUiDRVZgqvI/ipc4EEJLiYVdxHsKqu/kJo
B1qYXXxOQFSRUZ7UZLkVvn+JZtW6nnK/81fOeRKE3VIV7x5ejR9T8tB+dqv4sCMmj
jF2ehtevg94SMBSJjzPRcGp2pBdvvLBI83jZbxVAuUflLEE4BshNxIrTFkgO/HScz
Gd0426D3V8xfTii7e+VqX9JP3nmv57nsfwf4xrs2+cpZ568hhC9Z9N/aRswz8arso
rgOTcb3uPe8fkkakoIqNY7Hn/3s4YLl4SO6f/RIiEUE+vw+mT+cRK5YL9uphb4Wmg
LldHT+SbLRJXL9HGGRS8QJQf42SwH0IeCX2IHFC5uge/j8vOT8IaJFuuZ+iZNuu85
Dx/Xqy8+0xY/rWffR3cqIl6qsgeVC3aAPupPoC3ndb9R4VLCN/6N4RlY1IvePkYSg
PV8W7ufroY9rAGneyB0y1uA+wfetqIcwxFlqxq2GgSVl/koBs6jaeN/15CmwSrp9Y
i+VNotQZJFI+spIi45XM8dAgzIXNFia5VDJomy+NgvkvJf68De7UWxXo9WLebIMtW
C6ShwmNvg/hcdwfk6tCE0DMUjtOVYWcJSAnwFTiiOR+YcJkTHA8qDL16QxfZBVzNJ
lj4SOFvdv7w3KK+JM5OjlWVoDy2zRIE8IK1uGe39YXEnZbRlWP9EHf1f239hhZ4z0
/23Mj98bft2PSMcjWzioEDmzdCvba5lHBE5mrmXGjik/zQuypMXe4L8276RKA+Wc3
HJ3pYyE66dHT2cLpAs8Sjg3KzcEAwA7N8eedyMnIh6Wj5oShDqp2XVQoWt7MaTY1m
g==
</ViaThinkSoftSignature> */ ?>
<?php

/*
 * VNag - Nagios Framework for PHP
 * Developed by Daniel Marschall, ViaThinkSoft <www.viathinksoft.com>
 * Licensed under the terms of the Apache 2.0 license
 *
 * Revision 2018-07-15
 */

declare(ticks=1);

require_once __DIR__ . '/../../framework/vnag_framework.inc.php';
require_once __DIR__ . '/PhpMyAdminVersionCheck.class.php';

$job = new PhpMyAdminVersionCheck();
$job->run();
unset($job);
